#kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    app: cv-mostashkin

images:
    - name: nginx
      newName: nginx
      newTag: 1.23.2-alpine
    - name: cv
      newName: digitalacademydevops/cv
      newTag: main

resources:
- namespace.yaml
- cm.yaml
- deployment.yaml
- service.yaml